# Generated by Django 4.2.7 on 2023-11-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_images_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='productsimages')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=6)),
                ('discount', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('games', 'games'), ('consoles', 'consoles'), ('controllers', 'controllers'), ('accessories', 'accessories')], max_length=200)),
                ('count', models.IntegerField(default=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('uptade_at', models.DateTimeField(auto_now=True)),
                ('is_sale', models.BooleanField(default=False)),
            ],
        ),
    ]
